# -*- coding: utf-8 -*-
"""LRFS1.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smtVM0znFX_5bRKTZXYYmULSfQ7V9S7F
"""

# Commented out IPython magic to ensure Python compatibility.

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

df = pd.read_csv('dog_adoption_master.csv')

df.info()

df.head()

df.shape

nulls = df.isnull().sum()
nulls = nulls[nulls > 0]
print(nulls)

df ['days_to_return'] = df['days_to_return'].fillna(0)
print(df.isnull().sum())

print("filas duplicadas: ", df.duplicated().sum())
print("ID's duplicados: ", df['adoption_id'].duplicated().sum())

column_num = df.select_dtypes(include= [np.number]).columns
print(df[column_num].describe().T[['min','max']])

categorical_columns = ['size', 'breed_group', 'intake_type', 'medical_needs', 'home_type']
print('Categorias por columna: ')
for c in categorical_columns:
  print(f" {c}: {sorted(df[c].unique())}")

pd.set_option('display.max_columns', None)
df_clean = pd.get_dummies(df, columns=categorical_columns, dtype=int)
print('Shape despues del encoding: ', df_clean.shape)
df_clean.head()

df_clean.to_csv('dog_adoption_clean.csv', index=False)
print('Cleaned data saved to dog_adoption_clean.csv')

df_clean.describe()

fig, axes = plt.subplots(2,4, figsize= (16,7))
for ax, col in zip(axes.flat, column_num):
  ax.hist(df_clean[col], bins= 30, color= "#C7D3C0", edgecolor="white")
  ax.set_title(col)
axes.flat[-1].axis("off")
plt.tight_layout
plt.show()

fig, axes = plt.subplots(1,3, figsize=(14,4))
for ax, col in zip(axes, ['age_years', 'weight_kg', 'days_in_shelter']):
  ax.boxplot(df_clean[col], vert= True)
  ax.set_title(col)
plt.show()

fig, axes = plt.subplots(1, 5, figsize=(20,4))
for ax, col_name in zip(axes, categorical_columns):
  if col_name == 'size':
    cols = [c for c in df_clean.columns if c.startswith(f'{col_name}_') and c != 'size_home_mismatch']
  else:
    cols = [c for c in df_clean.columns if c.startswith(f'{col_name}_')]
  counts = df_clean[cols].sum().sort_values(ascending=False)
  ax.bar([c.replace(f'{col_name}_', '') for c in counts.index], counts.values, color="#A4B885")
  ax.set_title(col_name)
  ax.tick_params(axis='x', rotation = 45)
plt.show()

corr_cols = ['age_years', 'weight_kg', 'days_in_shelter', 'aggression_score',
             'anxiety_separation', 'reactivity_to_dogs', 'energy_level', 'training_level',
             'previously_returned', 'neutered', 'house_trained', 'returned']
plt.figure(figsize=(9,7))
sns.heatmap(df[corr_cols].corr(), annot=True, fmt=".2f", cmap="magma", center=0)
plt.title("Coorelacion entre variables numericas")
plt.show()

raw = pd.read_csv('dog_adoption_master.csv')
order = ['small', 'medium', 'large', 'xlarge']
plt.figure(figsize=(7,5))
sns.boxplot(data = raw, x= 'size', y='weight_kg', hue='size', order = order, palette='pastel')
plt.title('Peso (kg) por categoria de tamano')
plt.show()

df = pd.read_csv("dog_adoption_clean.csv")

feature_cols = df.select_dtypes(include= [np.number]).columns.tolist()
print(f"{len(feature_cols)} features numericas: ")
print(feature_cols)

X = df[feature_cols].to_numpy(dtype=float)
X.shape

def standarize_data(X):
  means= X.mean(axis=0)
  stds = X.std(axis=0)
  stds[stds == 0] = 1.0
  return(X-means) / stds

X_std = standarize_data(X)
print("media ~0:", np.round(X_std.mean(),2), "| std ~1:", np.round(X_std.std(),2))

coviariance_matrix = np.cov(X_std.T)
coviariance_matrix.shape

coviariance_matrix

eigen_values, eigen_vectors = np.linalg.eig(coviariance_matrix)

order = np.argsort(eigen_values)[::-1]
eigen_values = eigen_values[order].real
eigen_vectors = eigen_vectors[:, order].real

print("Primeros 5 eigenvalores: ", eigen_values[:5])

variance_explained = (eigen_values / eigen_values.sum()) *100
cum_var = np.cumsum(variance_explained)

for i in range(variance_explained.shape[0]):
  print(f"PC{i+1}: {variance_explained[i]: 5.2f}% acumulado: {cum_var[i]:6.2f}%")

plt.figure(figsize=(9,5))
plt.bar(range(1, len(variance_explained) +1), variance_explained, alpha = 0.6, label = "Varianza Individual")
plt.plot(range(1, len(cum_var)+1), cum_var, color="pink", marker='x', markersize=3, label="Varianza Acumulada")
plt.axhline(95, color='red', linestyle='--', label='95%')
plt.xlabel('Componente Principal')
plt.ylabel("% de varianza explicada")
plt.title("Scree Plot")
plt.legend()
plt.show()

n_com_95 = int(np.argmax(cum_var >=95) +1)
print(f'Se necesitan: {n_com_95} de {len(feature_cols)} componentes para explicar >= 95% de la varianza')

projection_matrix = eigen_vectors[:, :2]
X_pca = X_std.dot(projection_matrix)

com = pd.DataFrame(X_pca, columns=["PC1", "PC2"])
com["size"] = raw["size"].values
com.head()

plt.figure(figsize=(8,6))
sns.scatterplot(data=com, x='PC1', y='PC2', hue ='size', hue_order=["small", "medium", "large", "xlarge"], alpha = 0.4, s=15)
plt.title('Proyeccion PC1 vs PC2')
plt.show()
