# -*- coding: utf-8 -*-
"""LRFS2.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16KRZ2QGlCiz9_V43K6vMvDQ3m-X9jBV5
"""

# Commented out IPython magic to ensure Python compatibility.

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

df = pd.read_csv('dog_adoption_master.csv')

df.info()

df.head()

df.shape

nulls = df.isnull().sum()
nulls = nulls[nulls > 0]
print(nulls)

df ['days_to_return'] = df['days_to_return'].fillna(0)
print(df.isnull().sum())

print("filas duplicadas: ", df.duplicated().sum())
print("ID's duplicados: ", df['adoption_id'].duplicated().sum())

column_num = df.select_dtypes(include= [np.number]).columns
print(df[column_num].describe().T[['min','max']])

categorical_columns = ['size', 'breed_group', 'intake_type', 'medical_needs', 'home_type']
print('Categorias por columna: ')
for c in categorical_columns:
  print(f" {c}: {sorted(df[c].unique())}")

pd.set_option('display.max_columns', None)
df_clean = pd.get_dummies(df, columns=categorical_columns, dtype=int)
print('Shape despues del encoding: ', df_clean.shape)
df_clean.head()

df_clean.to_csv('dog_adoption_clean.csv', index=False)
print('Cleaned data saved to dog_adoption_clean.csv')

df_clean.describe()

fig, axes = plt.subplots(2,4, figsize= (16,7))
for ax, col in zip(axes.flat, column_num):
  ax.hist(df_clean[col], bins= 30, color= "#C7D3C0", edgecolor="white")
  ax.set_title(col)
axes.flat[-1].axis("off")
plt.tight_layout
plt.show()

fig, axes = plt.subplots(1,3, figsize=(14,4))
for ax, col in zip(axes, ['age_years', 'weight_kg', 'days_in_shelter']):
  ax.boxplot(df_clean[col], vert= True)
  ax.set_title(col)
plt.show()

fig, axes = plt.subplots(1, 5, figsize=(20,4))
for ax, col_name in zip(axes, categorical_columns):
  if col_name == 'size':
    cols = [c for c in df_clean.columns if c.startswith(f'{col_name}_') and c != 'size_home_mismatch']
  else:
    cols = [c for c in df_clean.columns if c.startswith(f'{col_name}_')]
  counts = df_clean[cols].sum().sort_values(ascending=False)
  ax.bar([c.replace(f'{col_name}_', '') for c in counts.index], counts.values, color="#A4B885")
  ax.set_title(col_name)
  ax.tick_params(axis='x', rotation = 45)
plt.show()

corr_cols = ['age_years', 'weight_kg', 'days_in_shelter', 'aggression_score',
             'anxiety_separation', 'reactivity_to_dogs', 'energy_level', 'training_level',
             'previously_returned', 'neutered', 'house_trained', 'returned']
plt.figure(figsize=(9,7))
sns.heatmap(df[corr_cols].corr(), annot=True, fmt=".2f", cmap="magma", center=0)
plt.title("Coorelacion entre variables numericas")
plt.show()

raw = pd.read_csv('dog_adoption_master.csv')
order = ['small', 'medium', 'large', 'xlarge']
plt.figure(figsize=(7,5))
sns.boxplot(data = raw, x= 'size', y='weight_kg', hue='size', order = order, palette='pastel')
plt.title('Peso (kg) por categoria de tamano')
plt.show()

df = pd.read_csv("dog_adoption_clean.csv")

feature_cols = df.select_dtypes(include= [np.number]).columns.tolist()
print(f"{len(feature_cols)} features numericas: ")
print(feature_cols)

X = df[feature_cols].to_numpy(dtype=float)
X.shape

def standarize_data(X):
  means= X.mean(axis=0)
  stds = X.std(axis=0)
  stds[stds == 0] = 1.0
  return(X-means) / stds

X_std = standarize_data(X)
print("media ~0:", np.round(X_std.mean(),2), "| std ~1:", np.round(X_std.std(),2))

coviariance_matrix = np.cov(X_std.T)
coviariance_matrix.shape

coviariance_matrix

eigen_values, eigen_vectors = np.linalg.eig(coviariance_matrix)

order = np.argsort(eigen_values)[::-1]
eigen_values = eigen_values[order].real
eigen_vectors = eigen_vectors[:, order].real

print("Primeros 5 eigenvalores: ", eigen_values[:5])

variance_explained = (eigen_values / eigen_values.sum()) *100
cum_var = np.cumsum(variance_explained)

for i in range(variance_explained.shape[0]):
  print(f"PC{i+1}: {variance_explained[i]: 5.2f}% acumulado: {cum_var[i]:6.2f}%")

plt.figure(figsize=(9,5))
plt.bar(range(1, len(variance_explained) +1), variance_explained, alpha = 0.6, label = "Varianza Individual")
plt.plot(range(1, len(cum_var)+1), cum_var, color="pink", marker='x', markersize=3, label="Varianza Acumulada")
plt.axhline(95, color='red', linestyle='--', label='95%')
plt.xlabel('Componente Principal')
plt.ylabel("% de varianza explicada")
plt.title("Scree Plot")
plt.legend()
plt.show()

n_com_95 = int(np.argmax(cum_var >=95) +1)
print(f'Se necesitan: {n_com_95} de {len(feature_cols)} componentes para explicar >= 95% de la varianza')

projection_matrix = eigen_vectors[:, :2]
X_pca = X_std.dot(projection_matrix)

com = pd.DataFrame(X_pca, columns=["PC1", "PC2"])
com["size"] = raw["size"].values
com.head()

plt.figure(figsize=(8,6))
sns.scatterplot(data=com, x='PC1', y='PC2', hue ='size', hue_order=["small", "medium", "large", "xlarge"], alpha = 0.4, s=15)
plt.title('Proyeccion PC1 vs PC2')
plt.show()

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression, Ridge

def scaling(X, mean = None, std = None):
  if mean is None:
    mean = X.mean(axis=0)
  if std is None:
    std = X.std(axis=0)
    std[std==0]= 1.0
  return (X -mean)/ std, mean, std

def mse(y_true, y_pred):
  return np.mean((y_true - y_pred)**2)

def mae(y_true, y_pred):
  return np.mean(np.abs(y_true-y_pred))

def r2(y_true, y_pred):
  return 1 -np.sum((y_true - y_pred)**2) / np.sum((y_true - y_true.mean())**2)

TARGET = "weight_kg"
NUMERIC_FEATURES = ["age_years", "aggression_score", "anxiety_separation",
    "reactivity_to_dogs", "energy_level", "training_level",]
BINARY_FEATURES = ["previously_returned", "neutered", "house_trained"]

size_cols = [c for c in df_clean.columns if c.startswith('size_') and c != "size_home_mismatch"]
breed_cols = [c for c in df_clean.columns if c.startswith("breed_group_")]
intake_cols = [c for c in df_clean.columns if c.startswith("intake_type_")]
medical_cols = [c for c in df_clean.columns if c.startswith("medical_needs_")]
dummy_cols = size_cols + breed_cols + intake_cols + medical_cols

feature_cols = NUMERIC_FEATURES + BINARY_FEATURES + dummy_cols
X = df_clean[feature_cols].to_numpy(dtype=float)
y = df_clean[TARGET].to_numpy(dtype=float)

VAL_SIZE = 0.2
TEST_SIZE = 0.2
SEED = 42

np.random.seed(SEED)
n = len(X)
idx = np.random.permutation(n)
n_test = int(n* TEST_SIZE)
n_val = int (n* VAL_SIZE)
test_idx = idx[:n_test]
val_idx = idx[n_test:n_test + n_val]
train_idx = idx[n_test + n_val:]


X_train, y_train = X[train_idx], y[train_idx]
X_val, y_val = X[val_idx], y[val_idx]
X_test, y_test = X[test_idx], y[test_idx]

n_numeric = len(NUMERIC_FEATURES)
X_train[:, :n_numeric], mean, std = scaling(X_train[:, :n_numeric])
X_val[:, :n_numeric], _, _ = scaling(X_val[:, :n_numeric], mean, std)
X_test[:, :n_numeric], _, _ = scaling(X_test[:, :n_numeric], mean, std)

print(f"Train: {X_train.shape}  Val: {X_val.shape}  Test: {X_test.shape}")

model2 = LinearRegression()
model2.fit(X_train, y_train)

pred_train = model2.predict(X_train)
pred_val = model2.predict(X_val)
pred_test = model2.predict(X_test)

print(f"Train -> MSE = {mse(y_train, pred_train):.3f}   R2 = {r2(y_train, pred_train):.4f}")
print(f"Val   -> MSE = {mse(y_val, pred_val):.3f}   R2 = {r2(y_val, pred_val):.4f}")
print(f"Test  -> MSE = {mse(y_test, pred_test):.3f}   RMSE = {mse(y_test, pred_test)**0.5:.3f}   "
      f"MAE = {mae(y_test, pred_test):.3f}   R2 = {r2(y_test, pred_test):.4f}")


mean_pred_val = np.full_like(y_val, y_train.mean())
dumb_mse_val = mse(y_val, mean_pred_val)

gap = mse(y_val, pred_val) - mse(y_train, pred_train)

print(f"\n--- Diagnostico de sesgo y varianza (Modelo 2.0) ---")
print(f"Baseline tonto (predecir siempre el promedio) MSE val = {dumb_mse_val:.3f}")
print(f"Gap (val - train) MSE = {gap:.3f}")

print("\nEfecto de Ridge (regularizacion L2 de sklearn) en el error de validacion:")
alphas_to_try = [0.1, 1, 5, 10, 25, 50, 100, 250, 500]
resultados_ridge = []
for a in alphas_to_try:
  ridge = Ridge(alpha=a)
  ridge.fit(X_train, y_train)
  pred_val_ridge = ridge.predict(X_val)
  val_mse_ridge = mse(y_val, pred_val_ridge)
  resultados_ridge.append((a, val_mse_ridge))
  print(f"  alpha = {a:6.1f}   val MSE = {val_mse_ridge:.3f}")

best_alpha = min(resultados_ridge, key=lambda t: t[1])[0]
print(f"\nMejor alpha segun validacion: {best_alpha}")

best_ridge = Ridge(alpha=best_alpha)
best_ridge.fit(X_train, y_train)
pred_test_ridge = best_ridge.predict(X_test)

print(f"\n--- Metricas finales en TEST (Modelo 2.0, Ridge alpha={best_alpha}) ---")
print(f"MSE  = {mse(y_test, pred_test_ridge):.3f}")
print(f"RMSE = {mse(y_test, pred_test_ridge)**0.5:.3f}")
print(f"MAE  = {mae(y_test, pred_test_ridge):.3f}")
print(f"R2   = {r2(y_test, pred_test_ridge):.4f}")

import matplotlib.pyplot as plt

plt.figure(figsize=(6, 6))
plt.scatter(y_test, pred_test, alpha=0.15, s=10)
lims = [0, max(y_test.max(), pred_test.max())]
plt.plot(lims, lims, "r--", label="prediccion perfecta")
plt.xlabel("peso real (kg)"); plt.ylabel("peso predicho (kg)")
plt.title("Peso real vs. peso predicho - Modelo 2.0 (test)")
plt.legend(); plt.grid(alpha=0.3); plt.show()


alphas_plot = [t[0] for t in resultados_ridge]
val_plot = [t[1] for t in resultados_ridge]
plt.figure(figsize=(7, 5))
plt.plot(alphas_plot, val_plot, "o-")
plt.xlabel("alpha"); plt.ylabel("MSE de validacion")
plt.title("Efecto de Ridge (regularizacion L2) - Modelo 2.0")
plt.grid(alpha=0.3); plt.show()